-- INSERT on table pms_product, Query: SELECT * FROM mall2.pms_product WHERE brand_id = '49' AND id IN ('1', '2');
INSERT INTO
    mall2.pms_product (
        id,
        brand_id,
        product_category_id,
        feight_template_id,
        product_attribute_category_id,
        name,
        pic,
        product_sn,
        delete_status,
        publish_status,
        new_status,
        recommand_status,
        verify_status,
        sort,
        sale,
        price,
        promotion_price,
        gift_growth,
        gift_point,
        use_point_limit,
        sub_title,
        description,
        original_price,
        stock,
        low_stock,
        unit,
        weight,
        preview_status,
        service_ids,
        keywords,
        note,
        album_pics,
        detail_title,
        detail_desc,
        detail_html,
        detail_mobile_html,
        promotion_start_time,
        promotion_end_time,
        promotion_per_limit,
        promotion_type,
        brand_name,
        product_category_name
    )
VALUES
    (
        1,
        49,
        7,
        0,
        0,
        '银色星芒刺绣网纱底裤',
        'newValue1',
        'xxxxx',
        1,
        1,
        1,
        1,
        1,
        100,
        0,
        '100.00',
        null,
        0,
        100,
        null,
        '111',
        '111',
        '120.00',
        100,
        20,
        '件',
        '1000.00',
        0,
        null,
        '银色星芒刺绣网纱底裤',
        '银色星芒刺绣网纱底裤',
        null,
        '银色星芒刺绣网纱底裤',
        '银色星芒刺绣网纱底裤',
        '银色星芒刺绣网纱底裤',
        '银色星芒刺绣网纱底裤',
        null,
        null,
        null,
        0,
        '七匹狼',
        '外套'
    );

INSERT INTO
    mall2.pms_product (
        id,
        brand_id,
        product_category_id,
        feight_template_id,
        product_attribute_category_id,
        name,
        pic,
        product_sn,
        delete_status,
        publish_status,
        new_status,
        recommand_status,
        verify_status,
        sort,
        sale,
        price,
        promotion_price,
        gift_growth,
        gift_point,
        use_point_limit,
        sub_title,
        description,
        original_price,
        stock,
        low_stock,
        unit,
        weight,
        preview_status,
        service_ids,
        keywords,
        note,
        album_pics,
        detail_title,
        detail_desc,
        detail_html,
        detail_mobile_html,
        promotion_start_time,
        promotion_end_time,
        promotion_per_limit,
        promotion_type,
        brand_name,
        product_category_name
    )
VALUES
    (
        2,
        49,
        7,
        0,
        0,
        '银色星芒刺绣网纱底裤2',
        'newValue1',
        'xxxxx',
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        '100.00',
        null,
        0,
        100,
        null,
        '111',
        '111',
        '120.00',
        100,
        20,
        '件',
        '1000.00',
        0,
        null,
        '银色星芒刺绣网纱底裤2',
        '银色星芒刺绣网纱底裤',
        null,
        '银色星芒刺绣网纱底裤',
        '银色星芒刺绣网纱底裤',
        '<p>银色星芒刺绣网纱底裤</p>',
        '<p>银色星芒刺绣网纱底裤</p>',
        null,
        null,
        null,
        0,
        '七匹狼',
        '外套'
    );

-- UPDATE on table pms_product_attribute, Query: SELECT * FROM mall2.pms_product_attribute WHERE type = 1 AND select_type = '2' AND id = 21;
UPDATE mall2.pms_product_attribute
SET
    product_attribute_category_id = 0,
    name = '适用对象3',
    select_type = 2,
    input_type = '888',
    input_list = 'QQQQ',
    sort = 0,
    filter_type = 0,
    search_type = 0,
    related_status = 0,
    hand_add_status = 0,
    type = 1
WHERE
    type = 1
    AND select_type = '2'
    AND id = 21
    AND id = 21;

-- EDIT on table pms_brand, Query: SELECT * FROM mall2.pms_brand WHERE sort = '500';
UPDATE mall2.pms_brand
SET
    name = '小米',
    sort = 1234
WHERE
    sort = '500'
    AND id = 6;