server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: admin2312
    url: jdbc:postgresql://localhost:5432/lihaomin
    username: postgres
    password: admin2312
    driver-class-name: org.postgresql.Driver

  task:
    scheduling:
      pool:
        size: 2
neo4j:
  uri: bolt://localhost:7687
  username: neo4j
  password: admin2312

logging:
  level:
    root: info

  




mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
